[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[prune]
  go-tests = true
  unused-packages = true