---
# api service, for service discovery from web
kind: Service
apiVersion: v1
metadata:
  name: registeel-api
  namespace: registeel
  labels:
    app: registeel-api
spec:
  selector:
    app: registeel-api
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30445
  type: NodePort
---
# api deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registeel-api
  namespace: registeel
  labels:
    app: registeel-api
spec:
  selector:
    matchLabels:
      app: registeel-api
  template:
    metadata:
      labels:
        app: registeel-api
    spec:
      containers:
      - name: registeel
        image: rossedman/registeel-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
