---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: 2018-11-12T22:21:12Z
  name: registeel-ctl
  namespace: registeel
---
# rbac permissiong for controller
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: registeel-ctl
rules:
- apiGroups: ["", "extensions", "apps"] # "" indicates the core API group
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "update", "edit", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: registeel-ctl
subjects:
- kind: ServiceAccount
  name: registeel-ctl
  namespace: registeel
roleRef:
  kind: ClusterRole
  name: registeel-ctl
  apiGroup: rbac.authorization.k8s.io
