---
# frontend service
kind: Service
apiVersion: v1
metadata:
  name: registeel-web
  namespace: registeel
  labels:
    app: registeel-web
spec:
  selector:
    app: registeel-web
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
# frontend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registeel-web
  namespace: registeel
  labels:
    app: registeel-web
spec:
  selector:
    matchLabels:
      app: registeel-web
  template:
    metadata:
      labels:
        app: registeel-web
    spec:
      containers:
      - name: registeel
        image: rossedman/registeel-web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
